### ISSUE TITLE
Annotated genome as input

### ISSUE THREAD

**Issue by iquasere** [nigyta/dfast_core#40]
Greetings!

I want to use DFAST to identify a set of proteins, instead of inputting an entire chromossome I want to skip the gene calling step and directly input protein sequences in FAA format. Is this possible with DFAST?

**Comment by nigyta** [comment]
Thanks for using DFAST.
Since DFAST is designed to handle the genome FASTA file as input, it cannot accept protein FASTA file.
However, if you already have a gene calling result in GFF format (such as an output from GeneMark-S2), you can provide it with `--gff` option and skip the gene calling process.

If you only have a FAA file, you cannot use DFAST, but you can search them against the DFAST reference database, which is stored in `db` directory under the directory DFAST is installed.

**Comment by iquasere** [comment]
Good to know, thank you ^^
