### ISSUE TITLE
Process aborted due to an error in DBsearch.

### ISSUE THREAD

**Issue by maxbranger** [nigyta/dfast_core#42]
Hello
I had an issue using recent version of blast and my own config file for running dfast.
I found this issue on abromics https://github.com/tseemann/abricate/issues/76 which helped me to try a fix.

I am using conda envs and the problem is gone when I use blast 2.7.1 version insted of more recent versions.

```
2022/03/23 11:12:08 Process aborted due to an error in DBsearch.
2022/03/23 11:12:08 Warning: [blastp] Examining 5 or more matches is recommended
```

So, the problem can be solved only by using an oldest version of blast by I guess it could be good to fix this if it is possible ?
As I understand, it is only a raised warning that doesnt block the execution of blast. But this raise an error on the pipeline that cancelled the process. 
 
At least, I hope it could help someone with the same issue.

**Comment by nigyta** [comment]
@maxbranger 
Thank you for letting me know. I was able to reproduce this with the latest version of BLASTP and have fixed it.

Please wait a few more days until I bump the version number, since I have another issue that I want to fix.

If you are in hurry, replace the file `dfc/components/baseComponent.py` with the latest one, which is abailable from [here](https://github.com/nigyta/dfast_core/blob/master/dfc/components/baseComponent.py)
